<html lang="en">
    <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Hello Hexlet!</title>
    </head>
    <body>
    <div class="col-lg-8 mx-auto p-4 py-md-5">
        <main>
        <H1>Анализатор страниц</H1>
                <H3>Бесплатно проверяйте сайты на SEO пригодность </H3>
                <main>
                        <form action="/users" method="get">
                                    <input type="search" name="term" value=""/>
                                    <input type="submit" value="Проверить" />
                                </form>
                    </main>
        </main>
    </div>
    </body>
</html>
